.TH LIVE555MEDIASERVER "1" "December 2016" "LIVE555MEDIASERVER" "User Commands"
.SH NAME
live555MediaServer \- RTSP server
.SH SYNOPSIS
live555MediaServer [options]
.SH DESCRIPTION
.sp
The "LIVE555 Media Server" is a complete RTSP server application. It can stream
several kinds of media file (which must be stored in the current working
directory - i.e., the directory from which you launch the application - or a
subdirectory.):
.IP
A MPEG Transport Stream file (with file name suffix ".ts")
.IP
A Matroska or WebM file (with filename suffix ".mkv" or ".webm")
.IP
An Ogg file (with filename suffix ".ogg", "ogv", or ".opus")
.IP
A MPEG-1 or 2 Program Stream file (with file name suffix ".mpg")
.IP
A MPEG-4 Video Elementary Stream file (with file name suffix ".m4e")
.IP
A H.264 Video Elementary Stream file (with file name suffix ".264")
.IP
A H.265 Video Elementary Stream file (with file name suffix ".265")
.IP
A VOB video+audio file (with file name suffix ".vob")
.IP
A DV video file (with file name suffix ".dv")
.IP
A MPEG-1 or 2 (including layer III - i.e., 'MP3') audio file (with file name suffix ".mp3")
.IP
A WAV (PCM) audio file (with file name suffix ".wav")
.IP
An AMR audio file (with file name suffix ".amr")
.IP
An AC-3 audio file (with file name suffix ".ac3")
.IP
An AAC (ADTS format) audio file (with file name suffix ".aac")
.sp
.SH SEE ALSO
.sp
\fIopenRTSP(1)\fP
.sp
\fIhttp://www.live555.com/mediaServer/\fP
