.TH LIVEMEDIAUTILS "1" "December 2016" "LIVEMEDIAUTILS" "User Commands"
.SH NAME
test* \- various utilities to test receiving and streaming of RTP streams
.SH SYNOPSIS
vobStreamer [\-i] [\-a|\-v] [\-p <RTSP-server-port-number>]
<VOB-files>
.SH DESCRIPTION
.sp
liblivemedia contains various utility programs to test streaming of receiving
RTP streams using various formats.
.SH SEE ALSO
.sp
\fIopenRTSP(1)\fP,
\fIplaySIP(1)\fP
.sp
\fIhttp://www.live555.com/liveMedia/#testProgs\fP
